/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  AuthMailAccounts: () => import('#controllers/auth_mail_accounts_controller'),
  Domains: () => import('#controllers/domains_controller'),
  MailAccountProfiles: () => import('#controllers/mail_account_profiles_controller'),
  MailAccounts: () => import('#controllers/mail_accounts_controller'),
  Mail: () => import('#controllers/mail_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  SesWebhook: () => import('#controllers/ses_webhook_controller'),
  Storage: () => import('#controllers/storage_controller'),
}
