/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Domains: () => import('#controllers/domains_controller'),
  MailAccounts: () => import('#controllers/mail_accounts_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
}
