/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  AuthMailAccounts: () => import('#controllers/auth_mail_accounts_controller'),
  Contacts: () => import('#controllers/contacts_controller'),
  Domains: () => import('#controllers/domains_controller'),
  ElgiopayWebhook: () => import('#controllers/elgiopay_webhook_controller'),
  Folders: () => import('#controllers/folders_controller'),
  MailAccountProfiles: () => import('#controllers/mail_account_profiles_controller'),
  MailAccounts: () => import('#controllers/mail_accounts_controller'),
  Mail: () => import('#controllers/mail_controller'),
  MailForwarding: () => import('#controllers/mail_forwarding_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  PublicDomains: () => import('#controllers/public_domains_controller'),
  RoleAliases: () => import('#controllers/role_aliases_controller'),
  SesWebhook: () => import('#controllers/ses_webhook_controller'),
  Signatures: () => import('#controllers/signatures_controller'),
  Storage: () => import('#controllers/storage_controller'),
  StorageOverview: () => import('#controllers/storage_overview_controller'),
  StripeWebhook: () => import('#controllers/stripe_webhook_controller'),
  Subscriptions: () => import('#controllers/subscriptions_controller'),
}
