/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactSchema extends BaseModel {
  static $columns = ['company', 'createdAt', 'email', 'firstName', 'id', 'lastName', 'mailAccountId', 'notes', 'phone', 'updatedAt'] as const
  $columns = ContactSchema.$columns
  @column()
  declare company: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string | null
  @column()
  declare mailAccountId: number
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DomainSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt', 'userId', 'verified'] as const
  $columns = DomainSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare verified: boolean | null
}

export class FileSchema extends BaseModel {
  static $columns = ['bucket', 'createdAt', 'id', 'key', 'mailAccountId', 'mimeType', 'originalName', 'size', 'updatedAt'] as const
  $columns = FileSchema.$columns
  @column()
  declare bucket: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare mailAccountId: number | null
  @column()
  declare mimeType: string | null
  @column()
  declare originalName: string
  @column()
  declare size: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FolderSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mailAccountId', 'name', 'updatedAt'] as const
  $columns = FolderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mailAccountId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MailAccountProfileSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'firstName', 'id', 'lastName', 'mailAccountId', 'updatedAt'] as const
  $columns = MailAccountProfileSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column()
  declare mailAccountId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MailAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'cuid', 'domainId', 'id', 'ownerEmail', 'password', 'resetPasswordToken', 'resetPasswordTokenExpiresAt', 'setuped', 'updatedAt', 'userId', 'username'] as const
  $columns = MailAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cuid: string
  @column()
  declare domainId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ownerEmail: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare resetPasswordToken: string | null
  @column.dateTime()
  declare resetPasswordTokenExpiresAt: DateTime | null
  @column()
  declare setuped: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare username: string
}

export class MailSchema extends BaseModel {
  static $columns = ['attachmentIds', 'bccAddresses', 'bodyHtml', 'bodyText', 'ccAddresses', 'createdAt', 'deleted', 'direction', 'folderId', 'fromEmail', 'id', 'important', 'isSpam', 'mailAccountId', 'replyTo', 'scheduledAt', 'sesMessageId', 'status', 'subject', 'toAddresses', 'updatedAt'] as const
  $columns = MailSchema.$columns
  @column()
  declare attachmentIds: any | null
  @column()
  declare bccAddresses: any | null
  @column()
  declare bodyHtml: string | null
  @column()
  declare bodyText: string | null
  @column()
  declare ccAddresses: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deleted: boolean
  @column()
  declare direction: string
  @column()
  declare folderId: number | null
  @column()
  declare fromEmail: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare important: boolean
  @column()
  declare isSpam: boolean
  @column()
  declare mailAccountId: number
  @column()
  declare replyTo: string | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column()
  declare sesMessageId: string | null
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare toAddresses: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currency', 'customerPhone', 'failureReason', 'id', 'provider', 'providerTransactionId', 'rawResponse', 'status', 'subscriptionId', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string
  @column()
  declare customerPhone: string | null
  @column()
  declare failureReason: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column()
  declare providerTransactionId: string | null
  @column()
  declare rawResponse: any | null
  @column()
  declare status: string
  @column()
  declare subscriptionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecordSchema extends BaseModel {
  static $columns = ['createdAt', 'domainId', 'id', 'name', 'priority', 'type', 'updatedAt', 'userId', 'value'] as const
  $columns = RecordSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare domainId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare priority: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare value: string
}

export class SignatureSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'facebook', 'id', 'includeInNewEmails', 'includeInReplies', 'includePhoto', 'instagram', 'jobTitle', 'linkedin', 'mailAccountId', 'name', 'phone', 'updatedAt', 'website'] as const
  $columns = SignatureSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare facebook: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare includeInNewEmails: boolean
  @column()
  declare includeInReplies: boolean
  @column()
  declare includePhoto: boolean
  @column()
  declare instagram: string | null
  @column()
  declare jobTitle: string | null
  @column()
  declare linkedin: string | null
  @column()
  declare mailAccountId: number
  @column()
  declare name: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare website: string | null
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['amountTotal', 'billingMonths', 'countryCode', 'createdAt', 'currency', 'currentPeriodEnd', 'id', 'mailboxQuantity', 'planId', 'provider', 'status', 'stripeCustomerId', 'stripeSubscriptionId', 'updatedAt', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column()
  declare amountTotal: number
  @column()
  declare billingMonths: number
  @column()
  declare countryCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string
  @column.dateTime()
  declare currentPeriodEnd: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mailboxQuantity: number
  @column()
  declare planId: string
  @column()
  declare provider: string
  @column()
  declare status: string
  @column()
  declare stripeCustomerId: string | null
  @column()
  declare stripeSubscriptionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'businessName', 'createdAt', 'email', 'emailVerificationCode', 'emailVerificationCodeExpiresAt', 'emailVerified', 'emailVerifiedAt', 'firstName', 'id', 'lastName', 'password', 'resetPasswordToken', 'resetPasswordTokenExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column()
  declare businessName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerificationCode: string | null
  @column.dateTime()
  declare emailVerificationCodeExpiresAt: DateTime | null
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare resetPasswordToken: string | null
  @column.dateTime()
  declare resetPasswordTokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
