/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FileSchema extends BaseModel {
  static table = 'files'
  static $columns = ['bucket', 'createdAt', 'id', 'key', 'mailAccountId', 'mimeType', 'originalName', 'size', 'updatedAt'] as const
  $columns = FileSchema.$columns
  @column()
  declare bucket: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare mailAccountId: number | null
  @column()
  declare mimeType: string | null
  @column()
  declare originalName: string
  @column()
  declare size: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DomainSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt', 'userId', 'verified'] as const
  $columns = DomainSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare verified: boolean | null
}

export class MailAccountProfileSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'firstName', 'id', 'lastName', 'mailAccountId', 'updatedAt'] as const
  $columns = MailAccountProfileSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column()
  declare mailAccountId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MailAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'cuid', 'domainId', 'id', 'ownerEmail', 'password', 'resetPasswordToken', 'resetPasswordTokenExpiresAt', 'setuped', 'updatedAt', 'userId', 'username'] as const
  $columns = MailAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cuid: string
  @column()
  declare domainId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ownerEmail: string | null
  @column({ serializeAs: null })
  declare password: string
  @column({ serializeAs: null })
  declare resetPasswordToken: string | null
  @column.dateTime()
  declare resetPasswordTokenExpiresAt: DateTime | null
  @column()
  declare setuped: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare username: string
}

export class MailSchema extends BaseModel {
  static table = 'mails'
  static $columns = ['attachmentIds', 'bccAddresses', 'bodyHtml', 'bodyText', 'ccAddresses', 'createdAt', 'direction', 'fromEmail', 'id', 'mailAccountId', 'replyTo', 'sesMessageId', 'status', 'subject', 'toAddresses', 'updatedAt'] as const
  $columns = MailSchema.$columns
  @column()
  declare attachmentIds: number[] | null
  @column()
  declare bccAddresses: string[] | null
  @column()
  declare bodyHtml: string | null
  @column()
  declare bodyText: string | null
  @column()
  declare ccAddresses: string[] | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare direction: 'sent' | 'received'
  @column()
  declare fromEmail: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mailAccountId: number
  @column()
  declare replyTo: string | null
  @column()
  declare sesMessageId: string | null
  @column()
  declare status: 'queued' | 'sent' | 'failed' | 'received'
  @column()
  declare subject: string
  @column()
  declare toAddresses: string[]
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecordSchema extends BaseModel {
  static $columns = ['createdAt', 'domainId', 'id', 'name', 'priority', 'type', 'updatedAt', 'userId', 'value'] as const
  $columns = RecordSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare domainId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare priority: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare value: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'emailVerificationCode', 'emailVerificationCodeExpiresAt', 'emailVerified', 'emailVerifiedAt', 'firstName', 'id', 'lastName', 'password', 'resetPasswordToken', 'resetPasswordTokenExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerificationCode: string | null
  @column.dateTime()
  declare emailVerificationCodeExpiresAt: DateTime | null
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare resetPasswordToken: string | null
  @column.dateTime()
  declare resetPasswordTokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
