/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ContactTransformer from '#transformers/contact_transformer'
import type DomainBrandingTransformer from '#transformers/domain_branding_transformer'
import type DomainTransformer from '#transformers/domain_transformer'
import type FileTransformer from '#transformers/file_transformer'
import type FolderTransformer from '#transformers/folder_transformer'
import type MailAccountProfileTransformer from '#transformers/mail_account_profile_transformer'
import type MailAccountTransformer from '#transformers/mail_account_transformer'
import type MailTransformer from '#transformers/mail_transformer'
import type RecordTransformer from '#transformers/record_transformer'
import type RoleAliasTransformer from '#transformers/role_alias_transformer'
import type SignatureTransformer from '#transformers/signature_transformer'
import type SubscriptionTransformer from '#transformers/subscription_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Contact = InferData<ContactTransformer>
  export namespace Contact {
    export type Variants = InferVariants<ContactTransformer>
  }
  export type DomainBranding = InferData<DomainBrandingTransformer>
  export namespace DomainBranding {
    export type Variants = InferVariants<DomainBrandingTransformer>
  }
  export type Domain = InferData<DomainTransformer>
  export namespace Domain {
    export type Variants = InferVariants<DomainTransformer>
  }
  export type File = InferData<FileTransformer>
  export namespace File {
    export type Variants = InferVariants<FileTransformer>
  }
  export type Folder = InferData<FolderTransformer>
  export namespace Folder {
    export type Variants = InferVariants<FolderTransformer>
  }
  export type MailAccountProfile = InferData<MailAccountProfileTransformer>
  export namespace MailAccountProfile {
    export type Variants = InferVariants<MailAccountProfileTransformer>
  }
  export type MailAccount = InferData<MailAccountTransformer>
  export namespace MailAccount {
    export type Variants = InferVariants<MailAccountTransformer>
  }
  export type Mail = InferData<MailTransformer>
  export namespace Mail {
    export type Variants = InferVariants<MailTransformer>
  }
  export type Record = InferData<RecordTransformer>
  export namespace Record {
    export type Variants = InferVariants<RecordTransformer>
  }
  export type RoleAlias = InferData<RoleAliasTransformer>
  export namespace RoleAlias {
    export type Variants = InferVariants<RoleAliasTransformer>
  }
  export type Signature = InferData<SignatureTransformer>
  export namespace Signature {
    export type Variants = InferVariants<SignatureTransformer>
  }
  export type Subscription = InferData<SubscriptionTransformer>
  export namespace Subscription {
    export type Variants = InferVariants<SubscriptionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
